name: melonmanager
description: Melon Manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  rive: ^0.7.2
  flutter_markdown: ^0.6.1 # Unused for now till I can get it to like not break my popups
  bitsdojo_window: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/melonbounce.riv
    - assets/images/DrawerBanner.jpg
    - assets/images/Icon.png

  fonts:
    - family: Jaapokki
      fonts:
        - asset: assets/fonts/jaapokki-regular.ttf
